class Country {
  final String name;
  final String code;
  final String dialCode;
  final String flag;

  const Country({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.flag,
  });

  static const List<Country> countries = [
    Country(name: 'السعودية', code: 'SA', dialCode: '+966', flag: '🇸🇦'),
    Country(name: 'الإمارات', code: 'AE', dialCode: '+971', flag: '🇦🇪'),
    Country(name: 'مصر', code: 'EG', dialCode: '+20', flag: '🇪🇬'),
    Country(name: 'الكويت', code: 'KW', dialCode: '+965', flag: '🇰🇼'),
    Country(name: 'قطر', code: 'QA', dialCode: '+974', flag: '🇶🇦'),
    Country(name: 'البحرين', code: 'BH', dialCode: '+973', flag: '🇧🇭'),
    Country(name: 'عُمان', code: 'OM', dialCode: '+968', flag: '🇴🇲'),
    Country(name: 'الأردن', code: 'JO', dialCode: '+962', flag: '🇯🇴'),
    Country(name: 'لبنان', code: 'LB', dialCode: '+961', flag: '🇱🇧'),
    Country(name: 'العراق', code: 'IQ', dialCode: '+964', flag: '🇮🇶'),
    Country(name: 'فلسطين', code: 'PS', dialCode: '+970', flag: '🇵🇸'),
    Country(name: 'سوريا', code: 'SY', dialCode: '+963', flag: '🇸🇾'),
    Country(name: 'اليمن', code: 'YE', dialCode: '+967', flag: '🇾🇪'),
    Country(name: 'المغرب', code: 'MA', dialCode: '+212', flag: '🇲🇦'),
    Country(name: 'تونس', code: 'TN', dialCode: '+216', flag: '🇹🇳'),
    Country(name: 'الجزائر', code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
    Country(name: 'ليبيا', code: 'LY', dialCode: '+218', flag: '🇱🇾'),
    Country(name: 'السودان', code: 'SD', dialCode: '+249', flag: '🇸🇩'),
    Country(name: 'موريتانيا', code: 'MR', dialCode: '+222', flag: '🇲🇷'),
    Country(name: 'جيبوتي', code: 'DJ', dialCode: '+253', flag: '🇩🇯'),
    Country(name: 'الصومال', code: 'SO', dialCode: '+252', flag: '🇸🇴'),
    Country(name: 'Comoros', code: 'KM', dialCode: '+269', flag: '🇰🇲'),
    Country(name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷'),
    Country(name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷'),
    Country(name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰'),
    Country(name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳'),
    Country(name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩'),
    Country(name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩'),
    Country(name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾'),
    Country(name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭'),
    Country(name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭'),
    Country(name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳'),
    Country(name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳'),
    Country(name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵'),
    Country(name: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷'),
    Country(name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸'),
    Country(name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧'),
    Country(name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪'),
    Country(name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷'),
    Country(name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹'),
    Country(name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸'),
    Country(name: 'Russia', code: 'RU', dialCode: '+7', flag: '🇷🇺'),
    Country(name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷'),
    Country(name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽'),
    Country(name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷'),
    Country(name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦'),
    Country(name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺'),
    Country(name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬'),
    Country(name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦'),
    Country(name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪'),
    Country(name: 'Ethiopia', code: 'ET', dialCode: '+251', flag: '🇪🇹'),
    Country(name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭'),
    Country(name: 'Chad', code: 'TD', dialCode: '+235', flag: '🇹🇩'),
    Country(name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪'),
    Country(name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱'),
    Country(name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳'),
    Country(name: 'Guinea', code: 'GN', dialCode: '+224', flag: '🇬🇳'),
    Country(name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯'),
    Country(name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬'),
    Country(name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱'),
    Country(name: 'Liberia', code: 'LR', dialCode: '+231', flag: '🇱🇷'),
    Country(name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫'),
    Country(name: 'Ivory Coast', code: 'CI', dialCode: '+225', flag: '🇨🇮'),
    Country(name: 'Cameroon', code: 'CM', dialCode: '+237', flag: '🇨🇲'),
    Country(name: 'DR Congo', code: 'CD', dialCode: '+243', flag: '🇨🇩'),
    Country(name: 'Congo', code: 'CG', dialCode: '+242', flag: '🇨🇬'),
    Country(name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬'),
    Country(name: 'Tanzania', code: 'TZ', dialCode: '+255', flag: '🇹🇿'),
    Country(name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼'),
    Country(name: 'Burundi', code: 'BI', dialCode: '+257', flag: '🇧🇮'),
    Country(name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼'),
    Country(name: 'Zambia', code: 'ZM', dialCode: '+260', flag: '🇿🇲'),
    Country(name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flag: '🇿🇼'),
    Country(name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿'),
    Country(name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴'),
    Country(name: 'Namibia', code: 'NA', dialCode: '+264', flag: '🇳🇦'),
    Country(name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼'),
    Country(name: 'Madagascar', code: 'MG', dialCode: '+261', flag: '🇲🇬'),
    Country(name: 'Mauritius', code: 'MU', dialCode: '+230', flag: '🇲🇺'),
    Country(name: 'Seychelles', code: 'SC', dialCode: '+248', flag: '🇸🇨'),
    Country(name: 'Eritrea', code: 'ER', dialCode: '+291', flag: '🇪🇷'),
    Country(name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫'),
    Country(name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵'),
    Country(name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰'),
    Country(name: 'Myanmar', code: 'MM', dialCode: '+95', flag: '🇲🇲'),
    Country(name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭'),
    Country(name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦'),
    Country(name: 'Mongolia', code: 'MN', dialCode: '+976', flag: '🇲🇳'),
    Country(name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬'),
    Country(name: 'Hong Kong', code: 'HK', dialCode: '+852', flag: '🇭🇰'),
    Country(name: 'Taiwan', code: 'TW', dialCode: '+886', flag: '🇹🇼'),
    Country(name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿'),
    Country(name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪'),
    Country(name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴'),
    Country(name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰'),
    Country(name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮'),
    Country(name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱'),
    Country(name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪'),
    Country(name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭'),
    Country(name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹'),
    Country(name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹'),
    Country(name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷'),
    Country(name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱'),
    Country(name: 'Czech Republic', code: 'CZ', dialCode: '+420', flag: '🇨🇿'),
    Country(name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴'),
    Country(name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺'),
    Country(name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦'),
  ];

  static Country get defaultCountry => countries[0];

  static List<Country> search(String query) {
    if (query.isEmpty) return countries;
    return countries.where((c) =>
      c.name.toLowerCase().contains(query.toLowerCase()) ||
      c.dialCode.contains(query) ||
      c.code.toLowerCase().contains(query.toLowerCase())
    ).toList();
  }
}
